name: Deploy to GitHub Pages

on:
  push:
<<<<<<< HEAD
    branches: ["main"]

=======
    branches: ["main", "master"]
>>>>>>> 1995c5cd6ca8eaccaf7be268103139e483d5eb55
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
=======
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
>>>>>>> 1995c5cd6ca8eaccaf7be268103139e483d5eb55
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
<<<<<<< HEAD
        run: npm install

      - name: Build
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
=======
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
>>>>>>> 1995c5cd6ca8eaccaf7be268103139e483d5eb55

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
<<<<<<< HEAD
        uses: actions/deploy-pages@v4
=======
        uses: actions/deploy-pages@v4
>>>>>>> 1995c5cd6ca8eaccaf7be268103139e483d5eb55
